version: '3'

services:
  node:
    container_name: fuel-consumption-web

    image: node:lts-alpine

    ports:
      - '8080:8080'

    volumes:
      - ./:/app

    working_dir: /app
  
    command: 'npm run serve'